apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: default-network
spec:
  rules:
  - host: insidethearts.test
    http:
      paths:
      - backend:
          serviceName: php-service
          servicePort: 80
